export class ProjectDTO {
    ProjectId! : number
    projectStatus: number=0;
    contractingCompanyId!: number;
    projectName!: string;
    city!: string;
    neighborhood!: string;
    isPurchaseInTender!: boolean;
    dateWinningTender: Date = new Date();
    isContractDevelopment!: boolean;
    contractDevelopmentFile: string = "";
    numberHakiraContract: string = "";
    numberLease: string = "";
    developmentPeriodEndDate: Date = new Date();
    isDiscounted!: boolean;
    isPurchaseTaxPaymentConfirmation!: boolean;
    purchaseTaxPaymentConfirmationFile: string = "";
    isAppreciationTaxPaymentConfirmation: boolean = false;
    appreciationTaxPaymentConfirmationFile: string = "";
    isSalesTaxPaymentConfirmation: boolean = false;
    salesTaxPaymentConfirmationFile: string = "";
    powerOfAttorneyToLawyerFile: string = "";
    lendingBank: number = 0;
    isPerselasia: boolean = false;
    fullAssetIdentificationBeforePerselasia: string = "";
    anotherIdentification: string = "";
    perselasiaFile: string = "";
    fullAssetIdentificationAfterPerselasia: string = "";
    bloc?: number;
    smooth?: number;
    smothArea?: number;
    isTookJointListingExpenses!: boolean;
    principalAmount: number = 0;
    collectionExpensesFrom1: Date = new Date();
    collectionAmount1: number = 0;
    collectionExpensesFrom2: Date = new Date();
    collectionAmount2: number = 0;
    collectionExpensesFrom3: Date = new Date();
    collectionAmount3: number = 0;
    insertDate!: Date;
    updateDate: Date = new Date();
    isRishumBaitMeshutafStarted: boolean = false;
    isPrepareWarningComment: boolean = false;
    isRishumBaitMeshutaf: boolean = false;
    hachiraContractFile: string = "";
    note: string = "";
    hachiraContractEndDate: Date = new Date();
    landOwnershipId: number = 0;
    mechozReshutMass: string = "";
    mechozReshutMassAddress: string = "";
    mechozMenaelMekarkaey: string = "";
    mechozMenaelMekarkaeyAddress?: string = "";
    mechozTabu: string = "";
    mechozTabuAddress: string = "";
    isDiscountedHachira: boolean = false;
    projectDrawingFile: string = "";
    isHachiraContract: boolean = false;
}